name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ClipGitter.csproj
      
    - name: Build
      run: dotnet build ClipGitter.csproj --configuration Release --no-restore
      
    - name: Clean Publish Directory
      run: rm -rf ./publish
      
    - name: Publish
      run: dotnet publish ClipGitter.csproj --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true --output ./publish
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2.0.9
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: ./publish/ClipGitter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
