name: Run Tests

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore ClipGitter.sln

    - name: Run tests
      run: dotnet test ClipGitter.sln --configuration Release --verbosity normal